### Assign a role to a user (only once, usually by admin)
POST http://localhost:3000/user/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiI5ZmNhZWJjNC0xOWZkLTQ5NDctODA2MC1hNmYwNTcxZjc0ZDIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYwNTM1MTIwLCJpYXQiOjE3NjA1MzE1MjAsImVtYWlsIjoiZ29rdWxrcjY1MjAwM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiZ29rdWxrcjY1MjAwM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ZmNhZWJjNC0xOWZkLTQ5NDctODA2MC1hNmYwNTcxZjc0ZDIifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2MDUzMTUyMH1dLCJzZXNzaW9uX2lkIjoiMjk4NDA2ODktNTk4MS00YmI1LWE2NDQtNjc3ZWI4MmM2MjdiIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.IJbz0FOQjw4Z7AqefGS6OeQJdV3-jxrjnWtyF9O2rkw



{
  "role": "admin",
  "email": "gokulkr65203@gmail.com"
}



