### Assign a role to a user (only once, usually by admin)
POST http://localhost:3000/auth/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiI1NGFkZmNkOC00ZjNhLTQ2MGEtOGY3MC1jN2M0OThjNzA4MDgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYwNDY3MDM5LCJpYXQiOjE3NjA0NjM0MzksImVtYWlsIjoiZ29rdWxrcjY1MjAwM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiZ29rdWxrcjY1MjAwM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI1NGFkZmNkOC00ZjNhLTQ2MGEtOGY3MC1jN2M0OThjNzA4MDgifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2MDQ2MzQzOX1dLCJzZXNzaW9uX2lkIjoiMTBjODUxN2UtMzNmZS00MzZkLTg1MWItM2ZmOGRlYzJhYjA0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.5zbV__EYHde0Ldr1lkstro94kXjH49SiZgvXF17a-uw


{
  "role": "admin",
  "email": "gokulkr65203@gmail.com"
}



