@supabase_url = {{$dotenv supabase_url}}
@supabase_api_key = {{$dotenv supabase_api_key}}

### Login
# @name login
POST http://localhost:54321/auth/v1/token?grant_type=password
Content-Type: application/json
apikey: {{supabase_api_key}}

{
  "email": "admin@example.com",
  "password": "admin123"
}

### Assign access token
@access_token={{login.response.body.access_token}}
@user_id={{login.response.body.user.id}}


### Assign a role to a user (only once, usually by admin)
POST http://localhost:3000/user/assign-role
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "role": "admin",
  "email": "newuser@example.com"
}

### Get details of the logged-in user
GET http://localhost:3000/users/me
Authorization: Bearer {{access_token}}

### block a user (only by admin)
POST http://localhost:3000/users/block-user/9b90bad5-95b2-45bf-838a-36a1d20f3c47
Content-Type: application/json
Authorization: Bearer {{access_token}}

### unblock a user (only by admin)
POST http://localhost:3000/users/unblock-user/9b90bad5-95b2-45bf-838a-36a1d20f3c47
Content-Type: application/json
Authorization: Bearer {{access_token}}

### List all users (only by admin)
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{access_token}}


