### Sign up a new user
POST http://localhost:54321/auth/v1/login
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "Password123"
}


### Assign a role to a user (only once, usually by admin)
POST http://localhost:3000/user/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc2MDYwODY2NX1dLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwiYXVkIjoiYXV0aGVudGljYXRlZCIsImVtYWlsIjoiZ29rdWxAMjAwM2dtYWlsLmNvbSIsImV4cCI6MTc2MDYxMjI2NSwiaWF0IjoxNzYwNjA4NjY1LCJpc19hbm9ueW1vdXMiOmZhbHNlLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJwaG9uZSI6IiIsInJvbGUiOiJhdXRoZW50aWNhdGVkIiwic2Vzc2lvbl9pZCI6IjQxNGE2MzM2LTExM2QtNDQ4MS05ZjQ0LTM4OTZjZGIzMDQzOSIsInN1YiI6IjI5OTQ2Mzk0LWUwMDktNDNiYy04MWNlLWViZDAyZWE2Y2VmNyIsInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJnb2t1bEAyMDAzZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInJvbGVzIjpbXSwic3ViIjoiMjk5NDYzOTQtZTAwOS00M2JjLTgxY2UtZWJkMDJlYTZjZWY3In19.av85oH6fxQeusAbX5avDafGL76iWdkrtGGBBi5SyYF4

{
  "role": "admin",
  "email": "newuser@example.com"
}

### Get details of the logged-in user
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbG



