### Assign a role to a user (only once, usually by admin)
POST http://localhost:3000/user/assign-role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiJkODhlODM1Yy1mYjA3LTRjOTItOGEzNS0zOTVlODZkM2Y5OTEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYwNTM2MzIyLCJpYXQiOjE3NjA1MzI3MjIsImVtYWlsIjoiZ29rdWw2NTIwMDNAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6Imdva3VsNjUyMDAzQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImQ4OGU4MzVjLWZiMDctNGM5Mi04YTM1LTM5NWU4NmQzZjk5MSJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYwNTMyNzIyfV0sInNlc3Npb25faWQiOiI1Y2ZkMTdiMC03MzU2LTQ5MzMtYmFiZS05NmQ2MjYwMjg0OTAiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.sEsR4tGb-rXzYV-fOyzU9g5Nx77sjqSeYIPxVgDJWus

{
  "role": "admin",
  "email": "email@example.com"
}



