# Enhanced CI/CD Pipeline with Feature Branch Support

name: Enhanced CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Run tests for both frontend and backend
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Run frontend tests
      run: npm test --workspace web-app
      continue-on-error: true
    
    - name: Run backend tests
      run: npm test --workspace api
      continue-on-error: true

  # Build both frontend and backend
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
    
    - name: Build frontend
      run: npm run build:web
    
    - name: Build backend
      run: npm run build:api
    
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: web-app/dist/
    
    - name: Upload backend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: api/dist/

  # Deploy feature branch previews
  deploy-feature:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    environment:
      name: preview
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: web-app/dist/
    
    - name: Download backend artifacts
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: api/dist/
    
    - name: Deploy to preview environment
      run: |
        echo "Deploying feature branch to preview environment"
        # Add your preview deployment commands here
        # Example: Deploy to Netlify/Vercel preview URLs

  # Deploy to staging environment
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: web-app/dist/
    
    - name: Download backend artifacts
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: api/dist/
    
    - name: Deploy frontend to staging
      run: |
        echo "Deploying frontend to staging environment"
        # Add your frontend deployment commands here
    
    - name: Deploy backend to staging
      run: |
        echo "Deploying backend to staging environment"
        # Add your backend deployment commands here

  # Deploy to production environment
  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download frontend artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: web-app/dist/
    
    - name: Download backend artifacts
      uses: actions/download-artifact@v4
      with:
        name: backend-build
        path: api/dist/
    
    - name: Deploy frontend to production
      run: |
        echo "Deploying frontend to production environment"
        # Add your frontend deployment commands here
    
    - name: Deploy backend to production
      run: |
        echo "Deploying backend to production environment"
        # Add your backend deployment commands here